### ISSUE TITLE
Availability of demo dataset

### ISSUE THREAD

**Issue by wu-yc** [LiQian-XC/sctour#1]
Hi Qian,

Thanks a lot for this fantastic package. This is really a great tool. 

In the tutorial of _scTour’s cross-data predictions_ and _Using scTour to infer cellular dynamics_, the demo data can not be found: 
```
'../../../mouse_endo_brain/raw_count_matrix_brain.txt'
'../../../mouse_endo_brain/Metadata.csv'
'../../../../EX_development_data/EX_development_human_cortex_10X.h5ad'
'../../../../EX_development_data/EX_development_human_cortex_DropSeq.h5ad'
'../../../../EX_development_data/EX_development_human_organoids_10X.h5ad'
'../../../../EX_development_data/EX_development_mouse_cortex_10X.h5ad'
```

Would you kindly upload them?

Cheers,
Yingcheng

**Comment by LiQian-XC** [comment]
@wu-yc, since the datasets are kind of large, I will try to upload them soon. Sorry for the inconvenience this has caused.

Best,
Qian

**Comment by LiQian-XC** [comment]
@wu-yc the download link for all the data have been added in the corresponding notebooks. Please let me know if you cannot download them.

**Comment by wu-yc** [comment]
@LiQian-XC Thanks so much for the kind help
