### ISSUE TITLE
Regarding the starting point question

### ISSUE THREAD

**Issue by wangweikai233** [LiQian-XC/sctour#16]
Hello, I think sctour is a very good tool, but if I have a known differentiation starting point cell subpopulation, can I manually specify it?
Best regards.

**Comment by LiQian-XC** [comment]
Hello. Unfortunately you cannot manually specify the starting point, as scTour infers pseudotime of cells directly from their transcriptome.

**Comment by wangweikai233** [comment]
I see, thanks
