### ISSUE TITLE
Trajectory inference of datasets with batch

### ISSUE THREAD

**Issue by wu-yc** [LiQian-XC/sctour#2]
Hi Qian,

Thanks again for this beautiful work.

I have lists of UMI matrix, integrated them by using scTransform or harmony (in R, and transfer it to h5ad), and generated the dimension reduction coordinates  (i.e. UMAP). Those lists of UMI matrix are generated at different timepoints and treatment conditions. When following the notebook of _scTour_inference_basic.ipynb_, it seems that the inferred trajectory is from batch 1 to batch 2 cells. 

Cheers,
Yingcheng

**Comment by LiQian-XC** [comment]
@wu-yc did you use the corrected counts as the input for scTour? I suggest to use the raw UMI count matrix from Cellranger as the input. Do you mind pasting your code here? It will be easier for me to check from there. Thanks!

**Comment by wu-yc** [comment]
Thanks for your kind support. Now i used the pre-computed UMAP (from Seurat) and then calculate the ptime. It finally works beautifully.
