### ISSUE TITLE
About the possibility of utilizing sctour on other modal data (i.e. scATAC-seq)

### ISSUE THREAD

**Issue by wu-yc** [LiQian-XC/sctour#3]
Hi Qian,

Since sctour is not based on the splicing hypothesis, is it possible to apply sctour to other modalities such as scATAC-seq or spatial transcriptomics data? 

Thanks again for this great algorithm.

Best,
Yingcheng

**Comment by LiQian-XC** [comment]
@wu-yc yes. scTour has been tested in one scATAC-seq dataset (supplementary fig 15 in the manuscript), but has not been tried in spatial data. In principle, it will work in spatial data as well but will test. Thanks!

**Comment by wu-yc** [comment]
This is really a fantastic package. Good luck with the paper!
